hyeon5819/Datescape_front

- static/js/report.js
- templates/report.html
> feat: report

- index.html
- static/js/map_search.js
- templates/map_search.html
이름을 잘못적었네요 merge하기전에 feat: 프론트에서 외부api로 지도정보 찾아서 해당정보로 백에서 좌표변환 후 db저장 작업.
> feat: 프론트 외부 api사

- static/js/emoticon_detail.js
- static/js/payment.js
- templates/emoticon_detail.html
> Merge: emoticon

- static/js/map_search.js
- templates/map_search.html
> feat: create article

- static/js/payment.js
- templates/emoticon_create.html
- templates/emoticon_detail.html
> feat: payment update

- static/js/map_search.js
- templates/map_search.html
> feat: article imgs

- static/js/admin_emoticon_detail_count.js
- static/js/admin_emoticon_list.js
- static/js/emoticon_list.js
- static/js/emoticon_temp_detail.js
- templates/admin_emoticon_detail_count.html
1. 임시저장 이모티콘 이미지 추가시 용량확인, 필드로 저장 추가
2. 이모티콘 관리자 - 판매량 페이지
> feat: emoticon

- static/css/article_detail.css
- static/js/article_detail.js
- templates/article_detail.html
> style: 지도부분 도로명주소 추가

- static/css/article_list.css
- static/js/article_list.js
혜린님 게시글 지도 연결 부분 + pagenation 추가 js 머지했습니다.
> feat: pagenation 프론트 연결

- index.html
- navbar.html
- static/js/admin.js
- static/js/admin_emoticon_detail_count.js
- static/js/admin_emoticon_list.js
- static/js/comment.js
- static/js/emoticon_create.js
- static/js/emoticon_detail.js
- static/js/emoticon_list.js
- static/js/emoticon_temp_detail.js
- static/js/emoticon_templist.js
- static/js/navbar.js
- templates/admin.html
- templates/admin_emoticon_detail_count.html
- templates/admin_emoticon_list.html
- templates/comment.html
- templates/emoticon_create.html
- templates/emoticon_detail.html
- templates/emoticon_list.html
- templates/emoticon_temp_detail.html
- templates/emoticon_templist.html
1. 관리자페이지, 관리자 권한 확인 후 리다이렉트
2. js로드 아래 위치, window.onload제거
> feat: admin page / admin confirm / refactor: code refactoring

- static/js/comment.js
- static/js/emoticon_create.js
- static/js/emoticon_detail.js
- static/js/emoticon_list.js
- static/js/emoticon_temp_detail.js
- static/js/emoticon_templist.js
- templates/comment.html
- templates/emoticon_create.html
- templates/emoticon_detail.html
- templates/emoticon_list.html
- templates/emoticon_temp_detail.html
- templates/emoticon_templist.html
1. 이모티콘 css
2. 이모티콘 만들기 -> 업로드 이미지 보여주기
> style: emoticon css / feat: emoticon create upload image view

- static/js/category_detail.js
- static/js/category_select.js
- templates/category.html
> feat: click category

- static/js/report.js
- templates/report.html
> merge: report

- index.html
- static/js/article_map_create.js
- static/js/article_update.js
- static/js/comment.js
- static/js/emoji.js
- templates/article_detail.html
- templates/article_update.html
게시글 상세 수정
태그 중복입력 방지, 문자열 백엔드 / 프론트엔드 통일
> feat: article update

- components/urls.js
- static/js/article_detail.js
- static/js/article_list.js
- templates/article_create.html
style: article_create, fix: tag add
> style: article_create, fix: tag add

- components/urls.js
- static/js/api.js
- static/js/article_create.js
- static/js/article_list.js
- static/js/article_update.js
- static/js/category_detail.js
- static/js/category_select.js
- static/js/emoticon_list.js
- static/js/emoticon_temp_detail.js
- static/js/emoticon_templist.js
- static/js/gps_api.js
- static/js/report.js
- static/js/search_index.js
- static/js/search_list.js
- templates/report.html
> feat: report id & type

- static/css/del_x.css
- static/js/admin_category.js
- templates/admin_category.html
> feat: create_category

- static/js/admin_category.js
- static/js/report.js
- templates/admin.html
> feat: admin category

- static/js/payment.js
결제완료 DB저장방식 변경에 따른 form data 수정 및 사용자 알림 방식 리팩토링
> fix: 결제완료 관련 DB저장 조작 이슈 수정 (refactor 결제완료시 DB저장 방식 변경)

- footer.html
- static/css/common.css
> style: 우측 구글폼,알림 버튼 위치조정

- static/js/mypage.js
> fix: my page

- gps.html
- static/js/navbar.js
- templates/article_create.html
> fix: event and something

- index.html
- static/js/search_index.js
> fix: styles

- static/js/article_create.js
- static/js/emoticon_buy_list.js
- templates/article_detail.html
- templates/emoticon_buy_list.html
- templates/emoticon_create.html
- templates/emoticon_detail.html
- templates/emoticon_list.html
- templates/emoticon_templist.html
feat: 구매 이모티콘 보기 및 설명 안내문구 추가
fix: 이모지 창 조절, 게시글 이미지 초과업로드시 파일 비워주기
> feat: 구매 이모티콘 보기 및 설명 안내문구 추가 / fix: 이모지 창 조절, 게시글 이미지 초과업로드시 파일 비워주기

- gps.html
- index.html
> style: 누락된 경로 추가

- templates/admin_category.html
> style: 어드민 카테고리 설명
